global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    static_configs:
      - targets: [ 'app:8080' ]
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]